apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^login', views.login, name = 'login'),
    url(r'^create', views.create, name = 'create'),
    url(r'^dashboard', views.dashboard, name = 'dashboard'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^', views.index, name = 'index'),
]

enigma/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^thing/', include('apps.thing.urls', namespace = 'thing')),
    url(r'^', include('apps.users.urls', namespace = 'users')),
]

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt

class UserManager(models.Manager):
    def registration_validator(self,postData):
        errors = {}
        #!!!!!Check if user already exists!!! By Email.
        emailsearch = User.objects.filter(email = postData['email'])
        if len(emailsearch)>0:
            errors['email'] = 'Account already exists'
        #!!!!!Check if user already exists!!! By Username.
        usersearch = User.objects.filter(username = postData['username'])
        if len(usersearch)>0:
            errors['username'] = 'Username already in use'
        #check if first name is at least one character long
        if len(postData['name'])<1:
            errors['name'] = "Name required"
        elif len(postData['name'])<3:
            errors['name'] = "Name too short"
        #check if last name is at least two characters long
        if len(postData['username'])<1:
            errors['username'] = "Username required"
        elif len(postData['username'])<2:
            errors['username'] = "Username too short"
        #check that passwords match
        if postData['pwd'] != postData['cpw']:
            errors['password'] = "Confirmation did not match password"
        if postData['pwd'] < 8:
            errors['password'] = "Passwords must be at least 8 characters long"
        return errors
    def login_validator(self,postData):
        errors = {}
        #check if user exists
        username = postData['username']
        usersearch = User.objects.filter(username = username)
        if len(usersearch) < 1:
            errors['username']='User not found'
        #verify password
        else:
            pwd = postData['pwd']
            temp = User.objects.get(username = username)
            hashedpw = temp.password
            if not bcrypt.checkpw(pwd.encode(), hashedpw.encode()):
                errors['password']='Unable to authenticate'
        return errors

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/users/forms.py
from django import forms
from django.forms import extras

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=255)
    pwd = forms.CharField(label='Password', max_length=255, widget = forms.PasswordInput)
class RegistrationForm(forms.Form):
    name = forms.CharField(label="Name", max_length = 255, widget = forms.TextInput)
    username = forms.CharField(label="Username", max_length = 255, widget = forms.TextInput)
    email = forms.CharField(label='Email', max_length=255, widget = forms.EmailInput)
    pwd = forms.CharField(label='Password', max_length=255, widget = forms.PasswordInput)
    cpw = forms.CharField(label='Confirm Password', max_length=255, widget = forms.PasswordInput)

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponseRedirect, HttpResponse, redirect
from django.contrib import messages
from .forms import LoginForm, RegistrationForm
from .models import User
from ..thing.models import Trip, Join
import bcrypt

# Create your views here.
def index(request):
    #start the journey
    login = LoginForm()
    register = RegistrationForm()
    return render(request, 'users/index.html', {'login':login, 'register': register})
def create(request):
    errors = User.objects.registration_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    else:
    #process registration form to add an account
        name = request.POST['name']
        username = request.POST['username']
        email = request.POST['email']
        pwd = request.POST['pwd']
        cpw = request.POST['cpw']
        hash1 = bcrypt.hashpw(pwd.encode(), bcrypt.gensalt())
        User.objects.create(name = name, username = username, email = email, password = hash1)
        temp = User.objects.get(email = email)
        request.session['id'] = temp.id
        return redirect('/dashboard')
def login(request):
    # process login form
    errors = User.objects.login_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    else:
        username = request.POST['username']
        temp = User.objects.get(username = username)
        request.session['id'] = temp.id
        print request.session['id']
        return redirect('/dashboard')
def dashboard(request):
    id = request.session['id']
    user = User.objects.get(id = id)
    alltrips = Trip.objects.all()
    othertrips = alltrips.exclude(planner=user)
    joins = Join.objects.filter(joiner = user)
    otherjoins = Join.objects.exclude(joiner = user)
    myjoins = Trip.objects.filter(joins = joins)
    prospective = othertrips.exclude(joins = joins)
    mytrips = Trip.objects.filter(planner = user)
    context = {
        'id':id,
        'name': user.name,
        'mytrips': mytrips,
        'myjoins': joins,
        'alltrips': prospective,
    }
    return render(request, 'users/dashboard.html', context)
def logout(request):
    del request.session['id']
    return redirect('/')

apps/users/templates/users/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
  </head>
  <body>
    <div class="container">
      <nav class = 'row'>
        <div class="ten columns">
          <h3 class = 'eight columns'>Hi, {{name}}!</h3>
        </div>
        <div class="two columns">
          <a href="/logout">Logout</a>
        </div>
      </nav>
      <div class="row">
        <h3>Your Trip Schedules</h3>
        <table class="u-full-width">
            <thead>
              <tr>
                <th>Destination</th>
                <th>Travel Start Date</th>
                <th>Travel End Date</th>
                <th>Plan</th>
              </tr>
            </thead>
            <tbody>
              {%for trip in mytrips%}
              <tr>
                <td><a href="/thing/show/{{trip.id}}">{{trip.destination}}</a></td>
                <td>{{trip.start}}</td>
                <td>{{trip.end}}</td>
                <td>{{trip.plan}}</td>
              </tr>
              {%endfor%}
              {%for join in myjoins%}
              <tr>
                <td><a href="/thing/show/{{trip.id}}">{{join.trip.destination}}</a></td>
                <td>{{join.trip.start}}</td>
                <td>{{join.trip.end}}</td>
                <td>{{join.trip.plan}}</td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
          <h3>Other User's Travel Plans</h3>
          <table class="u-full-width">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Destination</th>
                  <th>Travel Start Date</th>
                  <th>Travel End Date</th>
                  <th>Do You Want to Join?</th>
                </tr>
              </thead>
              <tbody>
                {%for trip in alltrips%}
                <tr>
                  <td>{{trip.planner.name}}</td>
                  <td><a href="/thing/show/{{trip.id}}">{{trip.destination}}</a></td>
                  <td>{{trip.start}}</td>
                  <td>{{trip.end}}</td>
                  <td><a href="/thing/join/{{trip.id}}">Join</a></td>
                </tr>
                {%endfor%}
              </tbody>
            </table>
            <div class="row">
              <div class="ten columns">
                <p></p>
              </div>
              <div class="two columns">
                <a href="/thing/add">Add Travel Plan</a>
              </div>
            </div>

          <!-- <h4>Recent Book Reviews</h4>
          {%for review in reviews%}
          <h5>{{review.book.title}}</h5>
          <p>Rating: {{review.stars}}</p>
          <a href="/users/{{review.reviewer.id}}">{{review.reviewer.first_name}}</a> says: {{review.review}}
          <p>Posted on: {{review.created_at}}</p>
          {%endfor%}
        </div>
        <div class="one-half column">
          <h5 class>Other Books with Reviews</h5>
          <div class="scroll">
            {%for book in books%}
            <p><a href="/books/{{book.id}}">{{book.title}}</a></p>
            {%endfor%} -->
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

apps/users/templates/users/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Registration Assignment</title>
    <link rel="stylesheet"
    8href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
  </head>
  <body>
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}
          </li>
          {% endfor %}
      </ul>
    {% endif %}
    <h1>Register</h1>
    <form action="{% url 'users:create' %}" method="post">
      {% csrf_token %}
      {{register.as_p}}
      <input type="submit" name = 'register' value="Submit" />
    </form>
    <h1>Login</h1>
    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      {{login.as_p}}
      <input type="submit" name = 'login' value="Submit" />
    </form>
  </body>
</html>